'use client';

import * as MantineComponents from '@mantine/core';

export const { AppShell } = MantineComponents;
export const { Box } = MantineComponents;
export const { Breadcrumbs } = MantineComponents;
export const { Timeline } = MantineComponents;
export const { TimelineItem } = MantineComponents;
export const { Flex } = MantineComponents;
export const { Header } = MantineComponents;
export const { Chip } = MantineComponents;
export const { Drawer } = MantineComponents;
export const { Burger } = MantineComponents;
export const { List } = MantineComponents;
export const { SimpleGrid } = MantineComponents;
export const { Container } = MantineComponents;
export const { Card } = MantineComponents;
export const { Paper } = MantineComponents;
export const { Divider } = MantineComponents;
export const { Stack } = MantineComponents;
export const { Group } = MantineComponents;
export const { Anchor } = MantineComponents;
export const { ActionIcon } = MantineComponents;
export const { ThemeIcon } = MantineComponents;
export const { Avatar } = MantineComponents;
export const { Image } = MantineComponents;
export const { Button } = MantineComponents;
export const { Badge } = MantineComponents;
export const { Title } = MantineComponents;
export const { Text } = MantineComponents;
