export const API_URL = process.env.NEXT_PUBLIC_STRAPI_URL;
export const API_TOKEN = process.env.NEXT_PUBLIC_STRAPI_TOKEN;

export const CONVERTKIT_KEY = process.env.NEXT_PUBLIC_CONVERTKIT_KEY;
export const CONVERTKIT_FORM_ID = process.env.NEXT_PUBLIC_CONVERTKIT_FORM_ID;
export const CONVERTKIT_API_SECRET =
  process.env.NEXT_PUBLIC_CONVERTKIT_API_SECRET;
